spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: your-client-id
            clientSecret: your-client-secret
          google:
            client-id: your-client-id
            client-secret: your-client-secret